<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/ytelse/arbeidogaktivitet/v1/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://nav.no/virksomhet/tjenester/ytelse/arbeidogaktivitet/v1/Binding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:arbeidogaktivitet="http://nav.no/virksomhet/tjenester/ytelse/arbeidogaktivitet/v1">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/ytelse/arbeidogaktivitet/v1" location="../arbeidogaktivitet.wsdl">
    </wsdl:import>
  <wsdl:binding name="ArbeidOgAktivitetYtelseBinding" type="arbeidogaktivitet:ArbeidOgAktivitetYtelse">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="finnYtelseListe">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="parameters" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="baksystemIkkeTilgjengelig">
        <soap:fault name="baksystemIkkeTilgjengelig" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ArbeidOgAktivitetYtelse">
    <wsdl:port name="ArbeidOgAktivitetYtelsePort" binding="tns:ArbeidOgAktivitetYtelseBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-arbeidOgAktivitetYtelse_v1Web/sca/ArbeidOgAktivitetYtelseWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
