version: '2.1'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

  topics:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Waiting until Kafka is ready'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating Kafka topic(s)'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tpts-arena-localhost-topic --replication-factor 1 --partitions 1

      echo -e 'The following topic(s) are now available'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Ready to go!'
      "