apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpts-arena
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  replicas:
    max: 1
    min: 1
  accessPolicy:
    inbound:
      rules:
        - application: tpts-tiltakspenger-mottak
          namespace: tpts
          cluster: dev-gcp
  ingresses:
    - https://tpts-arena.dev.intern.nav.no
    - https://tpts-arena.dev-fss-pub.nais.io
  liveness:
    path: /actuator/health/liveness
    initialDelay: 10
    timeout: 2
  readiness:
    path: /actuator/health/readiness
    initialDelay: 10
    timeout: 2
  prometheus:
    enabled: true
    path: /actuator/prometheus
  azure:
    application:
      enabled: true
      replyURLs:
        - "http://localhost:8080/swagger-ui/oauth2-redirect"
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvtpts-arena
        mountPath: /secrets/serviceuser