spring:
  application:
    name: "tpts-arena"
  main:
    banner-mode: off

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

app:
  arena:
    soap:
      sts:
        url: "https://security-token-service.dev.adeo.no/.well-known/openid-configuration"
        username: $SERVICEUSER_USERNAME
        password: $SERVICEUSER_PASSWORD
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"