spring:
  application:
    name: "tpts-arena"
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: "SSL"
      ssl:
        keystore:
          type: "PKCS12"
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: "PKCS12"
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}

server:
  shutdown: graceful

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

app:
  arena:
    kafka:
      consumer:
        topic: "aura.kafkarator-canary-dev-gcp"
        validators:
          - "no.nav.tpts.arena.validation.TimestampValidator"