spring:
  application:
    name: "tpts-arena"
  main:
    banner-mode: off

server:
  shutdown: graceful

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

app:
  azure:
    clientId: ${AZURE_APP_CLIENT_ID}
    tenantId: ${AZURE_APP_TENANT_ID}
  arena:
    soap:
      sts:
        url: "https://security-token-service.dev.adeo.no/.well-known/openid-configuration"
        username: "username"
        password: "password"
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"