spring:
  application:
    name: "tpts-arena"
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_JWKS_URI}
          jwk-set-uri: ${AZURE_ISSUER}

server:
  shutdown: graceful

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

app:
  arena:
    soap:
      sts:
        url: "https://security-token-service.dev.adeo.no/.well-known/openid-configuration"
        username: "username"
        password: "password"
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"