spring:
  application:
    name: "tpts-arena"
  main:
    banner-mode: off

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

app:
  azure:
    tenantId: ${AZURE_APP_TENANT_ID}
    clientId: ${AZURE_APP_CLIENT_ID}
    wellKnown: ${AZURE_APP_WELL_KNOWN_URL}
  arena:
    soap:
      sts:
        url: "https://sts-q1.preprod.local/SecurityTokenServiceProvider/"
        username: ${SERVICEUSER_USERNAME}
        password: ${SERVICEUSER_PASSWORD}
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"

no.nav.security.jwt:
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: "api://${AZURE_APP_CLIENT_ID}/.default"

springdoc:
  swagger-ui:
    oauth:
      client-id: ${AZURE_APP_CLIENT_ID}
      scopes:
        - "api://${AZURE_APP_CLIENT_ID}/.default"
      use-pkce-with-authorization-code-grant: true