spring:
  application:
    name: "tpts-arena"
  main:
    banner-mode: off

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

app:
  arena:
    soap:
      sts:
        url: "https://sts-q1.preprod.local/SecurityTokenServiceProvider/"
        username: ${SERVICEUSER_USERNAME}
        password: ${SERVICEUSER_PASSWORD}
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"

no.nav.security.jwt:
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
