#
# Run with program argument --spring.config.name=localhost for this configuration to take effect.
#
# Will keep looking for a localhost Kafka broker, see spring.kafka.bootstrap-servers.
# Also, you might want to change app.arena.kafka.consumer.topic to match your local setup.
#

spring:
  application:
    name: "tpts-arena"
  kafka:
    bootstrap-servers: "localhost:9092" # Your local Docker.
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

logging:
  config: classpath:logback-localhost.xml

app:
  azure:
    tenantId: "966ac572-f5b7-4bbe-aa88-c76419c0f851"
    clientId: "428e091a-5645-4c44-bb89-bb844401a4f0"
  arena:
    kafka:
      consumer:
        topic: "tpts-arena-localhost-topic"
    soap:
      sts:
        url: "https://security-token-service.dev.adeo.no/.well-known/openid-configuration"
        username: "username"
        password: "password"
      endpoints:
        ytelseskontrakt: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"